# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build-master

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'v14.18.1'
        cache: 'yarn'
    - run: yarn
    - run: yarn build-dist
  
    # Commits all changed files to the repository
    - name: Commit to the repo
      run: |
        git config --global user.name "Anant"
        git config --global user.email "anantnegi8@gmail.com"
        git add .
        # "echo" returns true so the build succeeds, even if no changed files
        git commit -m 'Update generated files' || echo
        git push
    
